name: fileaudioplayer
description: Audio player for local files. This plugin have ducking support to reduce the main audio volume while playing background music
version: 2.0.0
homepage: https://github.com/tapeo/file_audio_player

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: it.matteoricupero.fileaudioplayer
        pluginClass: FileaudioplayerPlugin
      ios:
        pluginClass: FileaudioplayerPlugin
